import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/NavBar";

const credibleregular = localFont({
  src: "./fonts/credibleRegular.otf",
  variable: "--font-credible",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${credibleregular.variable} ${credibleregular.variable} antialiased`}
      >
        <Navbar>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
